### ISSUE TITLE
TensorRT probelm;

### ISSUE THREAD

**Issue by Byronnar** [MukhlasAdib/SOLOv2_ONNX#3]
Great  project, Can you convert this model to tensorrt? I face some problem.

**Comment by MukhlasAdib** [comment]
@Byronnar Hi! Unfortunately, I never succeeded to convert it to TensorRT

**Comment by Byronnar** [comment]
> @Byronnar Hi! Unfortunately, I never succeeded to convert it to TensorRT

It's difficult. Thanks
